game:GetService("StarterGui"):SetCore("SendNotification",{Title="Antiafk",Text="Enabled"})
game:GetService("Players").LocalPlayer.Idled:Connect(function()
    game:GetService("VirtualUser"):CaptureController()
    game:GetService("VirtualUser"):ClickButton2(Vector2.new())
end)
